spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql=true:
  sql:
    init:
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql